### ISSUE TITLE
run ubsan in the pipeline for test_gctorture_1 

### ISSUE THREAD

**Issue by skrynski** [reactorlabs/rir#1257]
The current task definition  in the comment that ubsan is used but it isn't. We should run in  'sanitize'  mode

**# Run ubsan and gc torture**
```
test_gctorture_1:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_LLVM_OPT_LEVEL: 0
  stage: Run tests
  needs:
    - rir_container
  except:
    - schedules
  script:
    - /opt/rir/container/install-test-deps.sh
    **- cd /opt/rir/build/release**
    - R_GCTORTURE=5000 bin/gnur-make-tests check || $SAVE_LOGS
```

Otherwise, we could run `bin/gnur-make-tests check`   in the sanitize task.
